// <auto-generated />
namespace DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class StockTypeTable_Update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StockTypeTable_Update));
        
        string IMigrationMetadata.Id
        {
            get { return "201910250609351_StockTypeTable_Update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
